apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: in-k8s-resources
  annotations:
    kubernetes.io/ingress.class: "gce" 
spec:
  rules:
  - http:
      paths:
      # Swagger
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: auth-cluster 
            port:
              number: 8080
      - path: /v3
        pathType: Prefix
        backend:
          service:
            name: auth-cluster 
            port:
              number: 8080

      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: order-cluster 
            port:
              number: 8080
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: product-cluster 
            port:
              number: 8080
    
        
