apiVersion: v1
kind: Service
metadata:
  name: order-cluster
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"demo-backend-config"}}'
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: order