apiVersion: v1
kind: Service
metadata:
  name: control-center-lb
  namespace: confluent
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local  # 외부 클라이언트가 직접 노드로 접근 가능하게 설정
  ports:
    - name: control-center
      port: 9021        # 내부에서 사용하는 포트
      targetPort: 9021   # Kafka Pod의 포트
      protocol: TCP
  selector:
    app: controlcenter
