apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: haebyun/yoger-product-service-v8:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        envFrom:
        - secretRef:
            name: db-secret
        env:
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: product-cloud-secret
              key: s3-accessKey
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: product-cloud-secret
              key: s3-secretKey